### ISSUE TITLE
[BUG] Dead link to source code in readme

### ISSUE THREAD

**Issue by darigovresearch** [jpieper/bstrip#2]
The link in the readme to the source code points to a non-existent page

Page not found - https://github.com/jpieper/bstrip/blob/main/sw

Am assuming it should point to either of the following URLs
- https://github.com/jpieper/bstrip/tree/main/src
- https://github.com/jpieper/bstrip/blob/main/src/cutwire.py

**Comment by darigovresearch** [comment]
Merging pull request #3 would resolve this issue

**Comment by jpieper** [comment]
Thanks!
