### ISSUE TITLE
[FEATURE REQUEST] Circuit Diagram/Assembly Instructions

### ISSUE THREAD

**Issue by darigovresearch** [jpieper/bstrip#6]
It would be really helpful for anyone building to follow some assembly instructions or wiring diagram for bstrip.

Do you happen to have any reference assembly instructions or circuit diagrams that you used to build the design?

The exploded view helps but sometimes the order of assembly can make it hard to assemble certain sections towards the end.

**Comment by jpieper** [comment]
Nope.  There is really only one way to assemble and wire it up and it should be relatively straightforward.  If you have specific questions, don't hesitate to join the mjbots discord and ask: https://discord.gg/W4hUpBb
