### ISSUE TITLE
Possible use for 13 mm pvc pipe ?

### ISSUE THREAD

**Issue by CorentinLemaitre** [jpieper/bstrip#7]
Hello,

I have found your project on hackaday and it seems really great! 👏👏👏
I was wondering if there is a maximal diameter to use with ? 
I would like to cut pvc hose of 13 mm outter diameter and 10 mm inner diameter. 

I could make a fork of your project and change the cutting tool to make it work but may be there will be other issue with this design. 
As you have designed it, I think you will know if it will be possible to adapt or if it is not possible.

**Comment by jpieper** [comment]
Well, anything is possible with enough effort!  You would need a different cutting tool, and likely a different feed mechanism.

**Comment by CorentinLemaitre** [comment]
Ok thank you for your feedback, at least there is no big rock on the road. 

I will start digging on this direction. I think I will start in one or two month.

**Comment by jpieper** [comment]
Sounds good!
